#!/bin/bash
#PBS -l nodes=1:ppn=1,mem=10mb,walltime=10:00:00
#PBS -V
#PBS -N NAME
#pbs -m e
#pbs -M a.h.brown@warwick.ac.uk 
#cd $PBS_O_WORKDIR
./ising_gen TEMP FLIPS STEP BLOCK SIZE TYPE DIM FIELD METHOD


